#	$NetBSD$

NOMAN=	# defined

.include <bsd.own.mk>

HOSTPROGNAME=   ${_TOOL_PREFIX}cvslatest
HOST_SRCDIR=    usr.bin/cvslatest

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
