#	$NetBSD$
#

.PATH:  ${.CURDIR}/../../../../fs/ptyfs

LIB=	rumpfs_ptyfs
COMMENT=/dev/pts pseudo file system

SRCS+=	ptyfs_subr.c ptyfs_vfsops.c ptyfs_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
