#	$NetBSD$
#

.include <bsd.own.mk>

RUMPKERNCOMPS=	crypto sysproxy tty z
RUMPSYSEMUS=	sys_cygwin sys_linux sys_sunos

.if make(rumpdescribe)
RUMPKERNCOMPS+=	${RUMPSYSEMUS}
.endif

.if ${MKSLJIT} != "no" || make(rumpdescribe)
RUMPKERNCOMPS+=	sljit
.endif

.if ${MKZFS} != "no" || make(rumpdescribe)
RUMPKERNCOMPS+=    solaris
.endif

.for var in ${RUMPKERNCOMPS}
RUMPKERNLIBS+=lib${var}
RUMPKERNLDADD+=-lrumpkern_${var}
.endfor
