#	$NetBSD$
#

.PATH:  ${.CURDIR}/../../../../miscfs/kernfs

LIB=	rumpfs_kernfs
COMMENT=/kern fictional file system

SRCS=	kernfs_vfsops.c kernfs_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
