#	$NetBSD$

.include <bsd.own.mk>

SUBDIR+=	hello
#SUBDIR+=	luahello	# Nothing to build here, only text files
SUBDIR+=	ping		# Needs an additional helper program
SUBDIR+=	properties
SUBDIR+=	readhappy

.include <bsd.subdir.mk>
