#	$NetBSD$
#

.PATH:  ${.CURDIR}/../../../../fs/union

LIB=	rumpfs_union
COMMENT=union file system (fan-out layer)

SRCS=	union_subr.c union_vfsops.c union_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
