#	$NetBSD$

#NOMAN=

#.include <bsd.own.mk>

HOSTPROG=       ${_TOOL_PREFIX}makekeys
HOST_SRCDIR=	external/mit/xorg/tools/makekeys

#.PATH:  ${X11SRCDIR.X11}/src/util

#HOST_CPPFLAGS+= -I${DESTDIR}${X11INCDIR}

#SRCS=	makekeys.c

.include "${.CURDIR}/../Makefile.host"
#.include <bsd.hostprog.mk>
