#	$NetBSD$

HOSTPROGNAME=	${_TOOL_PREFIX}sortinfo
HOST_SRCDIR=	usr.bin/sortinfo

HOST_CPPFLAGS+=	-I. -I${TOOLDIR}/include/nbinclude

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
